// src/__test__/mockUsers.ts
import { ApiUser } from "@/types/users";

export const mockUsers: ApiUser[] = [
  {
    id: "1",
    organization: "Lendsqr",
    username: "johndoe",
    email: "john@example.com",
    phoneNumber: "+1234567890",
    dateJoined: "2023-01-15",
    status: "Active",
    profileImage: "https://example.com/avatar1.jpg",
    userInfo: {
      fullName: "John Doe",
      bvn: "12345678901",
      gender: "Male",
      maritalStatus: "Single",
      children: "None",
      typeOfResidence: "Rented",
      levelOfEducation: "BSc",
    },
    employmentInfo: {
      levelOfEducation: {
        fullName: "John Doe",
        bvn: "12345678901",
        gender: "Male",
        maritalStatus: "Single",
        children: "None",
        typeOfResidence: "Rented",
        levelOfEducation: "BSc",
      },
      employmentStatus: "Employed",
      sectorOfEmployment: "Tech",
      durationOfEmployment: "2 years",
      officeEmail: "john@company.com",
      monthlyIncome: "₦500,000",
      loanRepayment: "₦50,000",
    },
    socials: {
      twitter: "@johndoe",
      facebook: "johndoe",
      instagram: "@johndoe",
    },
    guarantors: [
      {
        name: "Jane Doe",
        phoneNumber: "+0987654321",
        email: "jane@example.com",
        relationship: "Sibling",
      },
    ],
    userTier: 1,
    accountBalance: "5000",
    bankName: "Test Bank",
    accountNumber: 1234567890,
  },
  {
    id: "2",
    organization: "TechCorp",
    username: "janesmith",
    email: "jane@example.com",
    phoneNumber: "+0987654321",
    dateJoined: "2023-02-20",
    status: "Inactive",
    profileImage: "https://example.com/avatar2.jpg",
    userInfo: {
      fullName: "Jane Smith",
      bvn: "09876543210",
      gender: "Female",
      maritalStatus: "Married",
      children: "2",
      typeOfResidence: "Owned",
      levelOfEducation: "MSc",
    },
    employmentInfo: {
      levelOfEducation: {
        fullName: "Jane Smith",
        bvn: "09876543210",
        gender: "Female",
        maritalStatus: "Married",
        children: "2",
        typeOfResidence: "Owned",
        levelOfEducation: "MSc",
      },
      employmentStatus: "Self-employed",
      sectorOfEmployment: "Finance",
      durationOfEmployment: "5 years",
      officeEmail: "jane@company.com",
      monthlyIncome: "₦1,000,000",
      loanRepayment: "₦100,000",
    },
    socials: {
      twitter: "@janesmith",
      facebook: "janesmith",
      instagram: "@janesmith",
    },
    guarantors: [
      {
        name: "John Smith",
        phoneNumber: "+1234567890",
        email: "john@example.com",
        relationship: "Sibling",
      },
    ],
    userTier: 2,
    accountBalance: "10000",
    bankName: "Another Bank",
    accountNumber: 987654321,
  },
];
